// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYDXgQ_T0FgL3NixVqHVvTPQYng-FYz0',
    appId: '1:772607665355:web:89dd5598df0b2eda7d674e',
    messagingSenderId: '772607665355',
    projectId: 'mynotes-2097a',
    authDomain: 'mynotes-2097a.firebaseapp.com',
    storageBucket: 'mynotes-2097a.appspot.com',
    measurementId: 'G-3SDDRMX0FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgKZ7JnYN5qoI1hQC0R2TiKRkJf1e91I',
    appId: '1:772607665355:android:0c31f1d4c6707b087d674e',
    messagingSenderId: '772607665355',
    projectId: 'mynotes-2097a',
    storageBucket: 'mynotes-2097a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhxJ_eMnLxDXTvnftvUaxKRx6ajhRVCM',
    appId: '1:772607665355:ios:0bc71b4164a5ffd77d674e',
    messagingSenderId: '772607665355',
    projectId: 'mynotes-2097a',
    storageBucket: 'mynotes-2097a.appspot.com',
    iosClientId: '772607665355-25tiq61s3shmu0ktbva4hrmu7v8v8iug.apps.googleusercontent.com',
    iosBundleId: 'com.AssahiAbdelhak.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhxJ_eMnLxDXTvnftvUaxKRx6ajhRVCM',
    appId: '1:772607665355:ios:0bc71b4164a5ffd77d674e',
    messagingSenderId: '772607665355',
    projectId: 'mynotes-2097a',
    storageBucket: 'mynotes-2097a.appspot.com',
    iosClientId: '772607665355-25tiq61s3shmu0ktbva4hrmu7v8v8iug.apps.googleusercontent.com',
    iosBundleId: 'com.AssahiAbdelhak.mynotes',
  );
}
